### ISSUE TITLE
シリアライズのフォーマットを検討

### ISSUE THREAD

**Issue by rog-works** [rog-works/py2cpp#36]
```yaml
structures:
  initializer:
    - 
  class:
...

entrypoint:
  class: !Ref class.a
```
